# Generated by Django 5.1.2 on 2024-10-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_reply_delay',
            field=models.IntegerField(blank=True, help_text='Delay in minutes', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
